import { z } from "zod";
export declare const TaskStatus: z.ZodEnum<["backlog", "in-progress", "review", "done", "blocked"]>;
export declare const TaskPriority: z.ZodEnum<["low", "medium", "high", "critical"]>;
export declare const RecoveryStrategy: z.ZodEnum<["resume", "restart"]>;
export declare const TaskFrontmatter: z.ZodObject<{
    id: z.ZodString;
    title: z.ZodString;
    status: z.ZodEnum<["backlog", "in-progress", "review", "done", "blocked"]>;
    priority: z.ZodDefault<z.ZodEnum<["low", "medium", "high", "critical"]>>;
    assigned_to: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    claimed_at: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    last_heartbeat: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    last_progress_at: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    heartbeat_interval: z.ZodDefault<z.ZodNumber>;
    needs_handoff: z.ZodDefault<z.ZodBoolean>;
    attempt_count: z.ZodDefault<z.ZodNumber>;
    previous_agents: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    depends_on: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    created_by: z.ZodDefault<z.ZodString>;
    recovery_strategy: z.ZodDefault<z.ZodEnum<["resume", "restart"]>>;
    project: z.ZodString;
}, "strip", z.ZodTypeAny, {
    status: "backlog" | "in-progress" | "review" | "blocked" | "done";
    title: string;
    priority: "low" | "medium" | "high" | "critical";
    tags: string[];
    id: string;
    assigned_to: string | null;
    claimed_at: string | null;
    last_heartbeat: string | null;
    last_progress_at: string | null;
    needs_handoff: boolean;
    attempt_count: number;
    previous_agents: string[];
    project: string;
    created_by: string;
    heartbeat_interval: number;
    depends_on: string[];
    recovery_strategy: "resume" | "restart";
}, {
    status: "backlog" | "in-progress" | "review" | "blocked" | "done";
    title: string;
    id: string;
    project: string;
    priority?: "low" | "medium" | "high" | "critical" | undefined;
    tags?: string[] | undefined;
    assigned_to?: string | null | undefined;
    claimed_at?: string | null | undefined;
    last_heartbeat?: string | null | undefined;
    last_progress_at?: string | null | undefined;
    needs_handoff?: boolean | undefined;
    attempt_count?: number | undefined;
    previous_agents?: string[] | undefined;
    created_by?: string | undefined;
    heartbeat_interval?: number | undefined;
    depends_on?: string[] | undefined;
    recovery_strategy?: "resume" | "restart" | undefined;
}>;
export type Task = z.infer<typeof TaskFrontmatter>;
export type TaskStatusType = z.infer<typeof TaskStatus>;
export declare const VALID_TRANSITIONS: Record<TaskStatusType, TaskStatusType[]>;
export declare function isValidTransition(from: TaskStatusType, to: TaskStatusType): boolean;
//# sourceMappingURL=schema.d.ts.map